# ⭐ numpy 

In [6]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# ⭐ creating array

In [3]:
l=[0,1,2,3,4,5]
l

[0, 1, 2, 3, 4, 5]

In [4]:
type(l)

list

# ⭐ convert list to array

In [7]:
arr=np.array(l)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
type(l)

list

In [14]:
print(arr.size)  # size of array

6


In [15]:
print(arr.ndim)    # no. of dimensions

1


In [13]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
 np.arange(8.4)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [16]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(20,13) # start is greater than end so empty array

array([], dtype=int32)

In [19]:
np.arange(-20,12)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11])

In [20]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [21]:
np.arange()

TypeError: arange() requires stop to be specified.

In [23]:
np.arange(10,30,5) # start index is 10 end index is 30 step index is 5

array([10, 15, 20, 25])

In [24]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [26]:
np.zeros(10)  

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10,dtype=int)  

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# ⭐ create 2d array

In [18]:
k=np.zeros((2,2),dtype=int)
k

array([[0, 0],
       [0, 0]])

In [19]:
print(k.ndim)

2


In [31]:
z=np.zeros([2,2] , dtype=int)
print(z)
print(type(z))

[[0 0]
 [0 0]]
<class 'numpy.ndarray'>


In [33]:
np.zeros([2,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.zeros((10,10),dtype=int)  # n-d array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [20]:
p=np.ones((3,3))
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [48]:
np.twos((2,3))   # we dont have this

AttributeError: module 'numpy' has no attribute 'twos'

In [21]:
print(p.ndim)

2


In [22]:
print(p+5)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


# ⭐ inserting elements
----------------------------------
np.insert(array name , index , value , axis)

axis = 0 -> row                                                     
axis = 1 -> col                                                 
axis = None -> flat


append(array name , value)  ----> to insert at end

In [39]:
np.insert(p,1,5,axis=None)   # inserting element in 1-d array

array([1., 5., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
#insert a new row at index 1
p2=np.array([[1,2],[3,4]]) 

newp2=np.insert(p2,1,[5,7],axis=0)  # axis none -- flat single line

newp2

array([[1, 2],
       [5, 7],
       [3, 4]])

In [50]:
ap=np.array([10,20,30])
nap=np.append(ap,[40,50])
nap

array([10, 20, 30, 40, 50])

# concatenate
-----------------

np.concatenate((array1,array2),axis=0)
axis=0  ----> vertical stacking
axis=1  ----> horizontal stacking

In [52]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])

res=np.concatenate((a1,a2),axis=0)
res

array([1, 2, 3, 4, 5, 6])

In [57]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([4,5,6,5])

res=np.concatenate((a1,a2),axis=1)  #axis=1 → ❌ invalid for 1D arrays, because they don’t have axis 1
res

AxisError: axis 1 is out of bounds for array of dimension 1

In [65]:
a1 = np.array([[1, 2, 3, 4]])  
a2 = np.array([[4, 5, 6, 5]]) 
res = np.concatenate((a1, a2), axis=1)
res

array([[1, 2, 3, 4, 4, 5, 6, 5]])

# Transpose

In [60]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Original:")
print(a)
print("Shape:", a.shape)

print("\nTransposed:")
print(a.T)
print("Shape:", a.T.shape)

Original:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [63]:
a1 = np.array([[1, 2, 3, 4]])  
a2 = np.array([[4, 5, 6, 5]]) 
res = np.concatenate((a1.T, a2.T), axis=1)  # .t transpose
res

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 5]])

# ⭐ delete

In [67]:
ap=np.array([10,20,30])
print(ap)
dp=np.delete(ap,2)
print(dp)

[10 20 30]
[10 20]


In [71]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

ra=np.delete(a,0,axis=0)
ra

array([[4, 5, 6]])

In [72]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

ra=np.delete(a,0,axis=1)
ra

array([[2, 3],
       [5, 6]])

# ⭐ Random

In [42]:
rand(3,2)

NameError: name 'rand' is not defined

In [43]:
random.rand(3,2)

NameError: name 'random' is not defined

In [45]:
np.random.rand(5)

array([0.23037411, 0.90863529, 0.98288522, 0.74285536, 0.66316478])

In [46]:
np.rand(6)

AttributeError: module 'numpy' has no attribute 'rand'

In [50]:
np.random.rand(3,4)  # 3 rows 4 columns with decimal vlues

array([[0.72439456, 0.13975605, 0.90735485, 0.64236403],
       [0.05353849, 0.03496967, 0.16546746, 0.90908461],
       [0.335521  , 0.17698026, 0.04846728, 0.17042775]])

In [56]:
np.random.randint(3,10) #Return random integers from `low` (inclusive) to `high` (exclusive).

3

In [59]:
np.random.randint(3,10,3) # last arg means that many random no.s in output

array([7, 8, 4])

In [61]:
np.random.randint(3,10,3,4) # only 3 ARGS

TypeError: Cannot interpret '4' as a data type

In [64]:
np.random.randint(10,40,(5,10)) # generate 2-d array (5*10) size with 10-40 of random no.s

array([[18, 22, 24, 11, 35, 20, 29, 38, 15, 26],
       [29, 34, 19, 39, 37, 22, 29, 28, 35, 12],
       [12, 21, 29, 13, 37, 15, 10, 38, 32, 38],
       [10, 28, 33, 14, 25, 38, 19, 34, 31, 22],
       [21, 12, 16, 36, 28, 10, 39, 35, 23, 31]])

# ⭐ reshape

In [65]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
np.arange(1,13).reshape(3,4)  # 3*4=12


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
np.arange(1,13).reshape(5,4)  #5*4=20  != 12 so error

ValueError: cannot reshape array of size 12 into shape (5,4)

In [75]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# ⭐ slicing in matrix

In [77]:
m=np.random.randint(10,30,(4,5))
m

array([[23, 25, 15, 12, 13],
       [25, 17, 24, 18, 11],
       [15, 16, 26, 11, 11],
       [26, 22, 15, 24, 28]])

In [79]:
type(m)

numpy.ndarray

In [80]:
m[:]

array([[23, 25, 15, 12, 13],
       [25, 17, 24, 18, 11],
       [15, 16, 26, 11, 11],
       [26, 22, 15, 24, 28]])

# stacking elements

In [74]:
aa1=np.array([1,2,3])
aa2=np.array([4,5,6])
print(np.vstack((aa1,aa2)))    # vstack() row wise
print(np.hstack((aa1,aa2)))    # hstack() col wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# splitting array
-----------------

np.split() : np.split(array, sections, axis=0 or 1)
General-purpose split.
You can split along any axis (default is axis=0 → rows).


np.hsplit() : Horizontal split → splits columns (axis=1).                         
np.vsplit() : Vertical split → splits rows (axis=0).

In [83]:
import numpy as np
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12],
              [13,14,15,16]])

# Split into 2 equal parts along columns (axis=1)
print(np.split(a, 2, axis=1))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [84]:
np.hsplit(a, 2)  # same as np.split(a, 2, axis=1)


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [85]:
np.vsplit(a, 2)  # same as np.split(a, 2, axis=0)


[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

# ⭐ diff. b/w [:]  slicing    and [,]  indexing

In [106]:
m[1:3]  

array([[25, 17, 24, 18, 11],
       [15, 16, 26, 11, 11]])

In [107]:
m[1,3]  

18

In [108]:
m

array([[23, 25, 15, 12, 13],
       [25, 17, 24, 18, 11],
       [15, 16, 26, 11, 11],
       [26, 22, 15, 24, 28]])

In [101]:
m[4,0]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [102]:
m[3,0]

26

In [104]:
m

array([[23, 25, 15, 12, 13],
       [25, 17, 24, 18, 11],
       [15, 16, 26, 11, 11],
       [26, 22, 15, 24, 28]])

In [105]:
m[1,-1]  # 1st row --- last column

11

In [109]:
m[0:-2]

array([[23, 25, 15, 12, 13],
       [25, 17, 24, 18, 11]])

In [110]:
m[-4,-2]

12

In [111]:
m[-3,2]

24

# ⭐ operations

In [115]:
a=np.random.randint(10,20,(10))
a

array([14, 17, 11, 12, 19, 18, 14, 19, 18, 19])

In [116]:
__name__

'__main__'

In [117]:
id(a)

1880412448464

In [118]:
arr

array([0, 1, 2, 3, 4, 5])

# ⭐ create 10*10 matrix between  0 - 100

In [120]:
arr2=np.random.randint(0,100,(10,10))
arr2 

array([[26, 53, 71, 73, 96, 60, 71, 46, 88, 91],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86],
       [87, 82, 65, 42, 76, 82,  7, 21, 57, 92],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [19, 93, 18,  0, 71, 90, 54,  6, 23, 19],
       [46, 24, 45, 98, 43, 62,  1, 65, 11, 83],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66],
       [25, 63, 76, 95, 58, 67, 88, 46, 62, 44],
       [18, 12, 97, 34, 37, 93, 14, 51, 21, 61],
       [25, 18, 19, 50, 82, 82, 86, 21, 25,  3]])

In [121]:
arr[:4]

array([0, 1, 2, 3])

In [122]:
arr2[:]

array([[26, 53, 71, 73, 96, 60, 71, 46, 88, 91],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86],
       [87, 82, 65, 42, 76, 82,  7, 21, 57, 92],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [19, 93, 18,  0, 71, 90, 54,  6, 23, 19],
       [46, 24, 45, 98, 43, 62,  1, 65, 11, 83],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66],
       [25, 63, 76, 95, 58, 67, 88, 46, 62, 44],
       [18, 12, 97, 34, 37, 93, 14, 51, 21, 61],
       [25, 18, 19, 50, 82, 82, 86, 21, 25,  3]])

In [123]:
arr2[0:5]

array([[26, 53, 71, 73, 96, 60, 71, 46, 88, 91],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86],
       [87, 82, 65, 42, 76, 82,  7, 21, 57, 92],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [19, 93, 18,  0, 71, 90, 54,  6, 23, 19]])

In [125]:
arr2[1,4]

62

In [127]:
arr2

array([[26, 53, 71, 73, 96, 60, 71, 46, 88, 91],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86],
       [87, 82, 65, 42, 76, 82,  7, 21, 57, 92],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [19, 93, 18,  0, 71, 90, 54,  6, 23, 19],
       [46, 24, 45, 98, 43, 62,  1, 65, 11, 83],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66],
       [25, 63, 76, 95, 58, 67, 88, 46, 62, 44],
       [18, 12, 97, 34, 37, 93, 14, 51, 21, 61],
       [25, 18, 19, 50, 82, 82, 86, 21, 25,  3]])

In [126]:
arr2[::-1]

array([[25, 18, 19, 50, 82, 82, 86, 21, 25,  3],
       [18, 12, 97, 34, 37, 93, 14, 51, 21, 61],
       [25, 63, 76, 95, 58, 67, 88, 46, 62, 44],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66],
       [46, 24, 45, 98, 43, 62,  1, 65, 11, 83],
       [19, 93, 18,  0, 71, 90, 54,  6, 23, 19],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [87, 82, 65, 42, 76, 82,  7, 21, 57, 92],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86],
       [26, 53, 71, 73, 96, 60, 71, 46, 88, 91]])

In [131]:
arr2[::-2]

array([[25, 18, 19, 50, 82, 82, 86, 21, 25,  3],
       [25, 63, 76, 95, 58, 67, 88, 46, 62, 44],
       [46, 24, 45, 98, 43, 62,  1, 65, 11, 83],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86]])

In [129]:
arr

array([0, 1, 2, 3, 4, 5])

In [128]:
arr[::-2]

array([5, 3, 1])

In [137]:
arr2

array([[26, 53, 71, 73, 96, 60, 71, 46, 88, 91],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86],
       [87, 82, 65, 42, 76, 82,  7, 21, 57, 92],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [19, 93, 18,  0, 71, 90, 54,  6, 23, 19],
       [46, 24, 45, 98, 43, 62,  1, 65, 11, 83],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66],
       [25, 63, 76, 95, 58, 67, 88, 46, 62, 44],
       [18, 12, 97, 34, 37, 93, 14, 51, 21, 61],
       [25, 18, 19, 50, 82, 82, 86, 21, 25,  3]])

In [135]:
arr2[::-3]

array([[25, 18, 19, 50, 82, 82, 86, 21, 25,  3],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [26, 53, 71, 73, 96, 60, 71, 46, 88, 91]])

In [138]:
arr2[0:10:3]

array([[26, 53, 71, 73, 96, 60, 71, 46, 88, 91],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66],
       [25, 18, 19, 50, 82, 82, 86, 21, 25,  3]])

In [136]:
arr2[:-3]

array([[26, 53, 71, 73, 96, 60, 71, 46, 88, 91],
       [57, 96, 18, 56, 62, 27, 78, 12,  4, 86],
       [87, 82, 65, 42, 76, 82,  7, 21, 57, 92],
       [21, 72, 56, 18, 19, 65, 24, 97, 11,  9],
       [19, 93, 18,  0, 71, 90, 54,  6, 23, 19],
       [46, 24, 45, 98, 43, 62,  1, 65, 11, 83],
       [91, 98,  6, 10, 50, 54, 37,  3, 78, 66]])

In [139]:
arr

array([0, 1, 2, 3, 4, 5])

In [140]:
arr.max()

5

In [141]:
arr.min()

0

In [142]:
arr.mean()

2.5

In [143]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [144]:
from numpy import * 
a=array([1,2,3,4,5])
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [24]:
from numpy import *  # * includes - 256 funcs. called internally
a=array([1,2,3,4,5])
print(median(a))
print(std(a))  # standard deviation
print(var(a)) # variance

3.0
1.4142135623730951
2.0


In [28]:
print(a.shape)   # Since a is a 1D array with 5 elements, the shape is (5,) — meaning one dimension with 5 elements.

(5,)


# ✅ Correct way to find mean without *

⚠️ Why not use { from numpy import * } ?
It imports everything into global space, which can cause conflicts and is not recommended.

Using np.mean() or np.median(a) is clearer and safer.

# mean = sum(data) / len(data)
-----------------------------------

In [153]:
import numpy as np
a = np.array([5,3,6,8,2])
print(np.mean(a))

4.8


# 📊 Median - middle value of a dataset when it is ordered from smallest to largest.


⭐ Always sort the data first before applying the formula.

👉 For Odd number of elements:
If the total number of elements (n) is odd,

Median = value at position (n + 1) / 2


----->📌 Example:
 
        Data: 3, 5, 7
        n = 3 (odd)
        Median = element at (3+1)/2 = 2nd position = **5**

👉 For Even number of elements:
If the total number of elements (n) is even,

Median = average of the values at positions n/2 and (n/2) + 1

-----> 📌 Example:

        Data: 2, 4, 6, 8
        n = 4 (even)
        Median = (4 + 6) / 2 = **5**

In [157]:
import numpy as np
a = np.array([2, 4, 6, 8])
print(np.median(a))

5.0


# 
-----------------------------------------------------------------------------

In [158]:
arr

array([0, 1, 2, 3, 4, 5])

In [159]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [160]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [161]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [162]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [165]:
arr

array([0, 1, 2, 3, 4, 5])

# ⭐ order
-----------------------------------------------------------------------------


In [173]:
arr.reshape(3,2,order='C')  # used to show data in diff

array([[0, 1],
       [2, 3],
       [4, 5]])

In [174]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [168]:
arr.reshape(3,2,order='A')  # similar to c type

array([[0, 1],
       [2, 3],
       [4, 5]])

# ⭐ Indexing
---------------------------------------------

In [171]:
mat=np.arange(0,100).reshape(10,10)

In [172]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
row,col=4,5

In [180]:
mat[row,col]  # array can understand by values and variables as well

45

In [181]:
col=6

In [183]:
mat[5]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [185]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# print a col from matrix

In [186]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [187]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [188]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [190]:
mat[:,3:5]   # to print set of col only

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [192]:
mat[2:6,2:4]  #to print certain rows and only few col from it

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [193]:
mat[1:2,2:4]

array([[12, 13]])

In [194]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# ⭐ ravel and flatten : 
are used to convert multi-dimensional arrays into a 1D array, but they have some key differences.


---------------------
= .ravel()    ---->   it returns a view - original array gets affected, Changes made to the raveled array may affect the original array              
= .flatten()  ---->   it retuens a copy - original array is not affected,Changes made to the flattened array do not affect the original array.

In [33]:
ar=np.array([[10,20,30] , [40,50,60]])

print(ar.ravel())
print(ar.flatten())

# ouptput same

[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [34]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
b[0] = 100
print(a)  # Original array is unchanged
print(b)  # Flattened copy

[[1 2]
 [3 4]]
[100   2   3   4]


In [35]:
c = a.ravel()
c[0] = 200
print(a)  # Original array might be changed if `ravel()` returned a view
print(c)

[[200   2]
 [  3   4]]
[200   2   3   4]


In [32]:
ar

array([[10, 20, 30],
       [40, 50, 60]])

# ⭐⭐⭐  MASKING

In [195]:
mat # we aslo called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
id(mat)

1880415058992

In [202]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [201]:
mat[mat>=50].reshape(5,10)

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[mat<50].reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [204]:
mat[mat==50]

array([50])

In [206]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Real world Application
------------
to apply discount on all the products

In [87]:
prices=np.array([100,200,300,400,500])
discount=10
final_price=prices-(prices*discount/100)
print(final_price)

[ 90. 180. 270. 360. 450.]


# Broadcasting and vectorization

In [89]:
# this is not possible in python .... here vector is expanded and added in both rows of the matrix
matrix=np.array([[1,2,3],[4,5,6]]) 
vector=np.array([10,20,30])
res=matrix+vector
print(res)

[[11 22 33]
 [14 25 36]]


In [91]:
# incompatible type as mis-match of dimensions
matrix=np.array([[1,2,3],[4,5,6]]) 
vector=np.array([10,20,30,40])
res=matrix+vector
print(res)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [94]:
matrix=np.array([[1,2,3],[4,5,6]]) 
res=matrix*2
print(res)

[[ 2  4  6]
 [ 8 10 12]]


In [86]:
import random 

def gt(length):
    digits='01234567'
    otp=''.join(random.choice(digits) for _ in range(length))
    return otp

length=4
otp=gt(length)
print(f"otp:{otp}")


otp:2311


# ⭐ Handling Missing Values

In [96]:
import numpy as np

arrayy = np.array([1,2,np.nan,4,np.nan,6])
np.isnan(arrayy)

array([False, False,  True, False,  True, False])

In [111]:
# replace them 

arrayy = np.array([1,2,np.nan,4,np.nan,6])
cleaned= np.nan_to_num(arrayy)
cleaned

array([1., 2., 0., 4., 0., 6.])

In [102]:
arrayy = np.array([1,2,np.nan,4,np.nan,6])
cleaned= np.nan_to_num(arrayy,nan=20)
cleaned

array([ 1.,  2., 20.,  4., 20.,  6.])

In [103]:
arrayy = np.array([1,2,np.inf,4,-np.inf,6])
cleaned= np.isinf(arrayy)
cleaned

array([False, False,  True, False,  True, False])

In [110]:
# replace them 

arrayy = np.array([1,2,np.inf,4,-np.inf,6])
cleaned= np.nan_to_num(arrayy,posinf=100,neginf=56)
cleaned

array([  1.,   2., 100.,   4.,  56.,   6.])